### ISSUE TITLE
Migration to new CDS-Beta API personal access token (for ERA5) tosses a ValueError

### ISSUE THREAD

**Issue by AstroCGHA** [kylejgillett/sounderpy#26]
Since its September already, the CDS used for querying ERA5 will migrate to CDS-Beta (Please see this [forum](https://confluence.ecmwf.int/display/CKB/Please+read%3A+CDS+and+ADS+migrating+to+new+infrastructure%3A+Common+Data+Store+%28CDS%29+Engine) and the new [CDS-Beta interface](https://cds-beta.climate.copernicus.eu/how-to-api#use-the-cds-api-client-for-data-access)). 

It requires updating the API credentials on the .cdsapirc file. However, upon updating the credentials and trying it on a new conda environment with Spy (SounderPy) ver. 3.0.4, it tosses an error message (most likely related to xarray package).

```
ValueError: found the following matches with the input file in xarray's IO backends: ['h5netcdf']. But their dependencies may not be installed, see:
https://docs.xarray.dev/en/stable/user-guide/io.html 
```

Is there a way to resolve this issue? Btw, all dependencies were downloaded for the xarray, so as for Spy. So, its quite strange that it tosses an error message.

**Comment by kylejgillett** [comment]
This issue has been resolved and updates have been made to SounderPy's ``get_model_data()`` function to accommodate the new CDS API update. 

This fix will be implemented in the next release of SounderPy. Thus, I will close this issue.

For other readers, if you come across this issue because ERA5 data access is not working for you, note that you must update your ERA5 CDSAPI account and API access keys to the new CDSAPI Beta.
